### ISSUE TITLE
Suggest repo rename

### ISSUE THREAD

**Issue by redhatrises** [CrowdStrike/ansible_collection_crowdstrike#8]
Rather than having a single repo per role, I think it makes sense to update this repo name to `ansible_collection_crowdstrike` at a minimum... maybe to `ansible_collection_crowdstrike_falcon` at most if we are only going to do falcon ansible roles.

**Comment by shawndwells** [comment]
``ansible_collection_crowdstrike`` seems ideal, so we can grow into providing content for CSPM and CWP and Preempt and whatever else is next. Made you repo admin to make the change.

**Comment by redhatrises** [comment]
This is now done. CLosing
